services:
  server:
    image: ghcr.io/vasylykserhiy/utility_hub/server:prod
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      args:
        NODE: production
    container_name: server
    ports:
      - "8080:8080"
  
  web:
    image: ghcr.io/vasylykserhiy/utility_hub/web:prod
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NODE: production
    container_name: web
    ports:
      - "3000:3000"
